/* iPad2Spotify - intentionally ES5/XHR compatible for iOS 9 Safari. */
(function () {
  'use strict';
  var AUTH = 'https://accounts.spotify.com/authorize';
  var TOKEN = 'https://accounts.spotify.com/api/token';
  var API = 'https://api.spotify.com/v1';
  var REDIRECT = window.location.protocol + '//' + window.location.host + window.location.pathname;
  var SCOPES = 'user-read-currently-playing user-read-playback-state user-modify-playback-state';
  var token = localStorage.getItem('spotify_access_token');
  var expiresAt = parseInt(localStorage.getItem('spotify_expires_at') || '0', 10);
  var current = null;
  var pollTimer = null;
  var progressTimer = null;
  var lastPoll = 0;

  function byId(id) { return document.getElementById(id); }
  function encode(value) { return encodeURIComponent(value).replace(/%20/g, '+'); }
  function params(values) { var out = [], key; for (key in values) { if (values.hasOwnProperty(key)) out.push(encode(key) + '=' + encode(values[key])); } return out.join('&'); }
  function randomString(length) { var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~', out = '', i; for (i = 0; i < length; i += 1) out += chars.charAt(Math.floor(Math.random() * chars.length)); return out; }
  function base64Url(bytes) { var binary = '', i, raw; for (i = 0; i < bytes.length; i += 1) binary += String.fromCharCode(bytes[i]); raw = btoa(binary); return raw.replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_'); }

  /* Small SHA-256 implementation: no Web Crypto or TextEncoder required. */
  function sha256(ascii) {
    var mathPow = Math.pow, maxWord = mathPow(2, 32), result = '', words = [], asciiBitLength = ascii.length * 8, hash = sha256.h = sha256.h || [], k = sha256.k = sha256.k || [], primeCounter = k.length, isComposite = {}, i, j, w, a, e, t1, t2;
    for (i = 2; primeCounter < 64; i += 1) { if (!isComposite[i]) { for (j = 0; j < 313; j += i) isComposite[j] = i; hash[primeCounter] = (mathPow(i, .5) * maxWord) | 0; k[primeCounter++] = (mathPow(i, 1 / 3) * maxWord) | 0; } }
    ascii += '\x80'; while (ascii.length % 64 - 56) ascii += '\x00';
    for (i = 0; i < ascii.length; i += 1) { j = ascii.charCodeAt(i); if (j >> 8) return ''; words[i >> 2] |= j << ((3 - i) % 4 * 8); }
    words[words.length] = ((asciiBitLength / maxWord) | 0); words[words.length] = asciiBitLength;
    for (j = 0; j < words.length;) { w = words.slice(j, j += 16); a = hash.slice(0); for (i = 0; i < 64; i += 1) { w[i] = i < 16 ? w[i] : (w[i - 16] + (((w[i - 15] << 25) | (w[i - 15] >>> 7)) ^ ((w[i - 15] << 14) | (w[i - 15] >>> 18)) ^ (w[i - 15] >>> 3)) + w[i - 7] + (((w[i - 2] << 15) | (w[i - 2] >>> 17)) ^ ((w[i - 2] << 13) | (w[i - 2] >>> 19)) ^ (w[i - 2] >>> 10))) | 0; t1 = (a[7] + (((a[4] << 26) | (a[4] >>> 6)) ^ ((a[4] << 21) | (a[4] >>> 11)) ^ ((a[4] << 7) | (a[4] >>> 25)) ) + ((a[4] & a[5]) ^ (~a[4] & a[6])) + k[i] + w[i]) | 0; t2 = ((((a[0] << 30) | (a[0] >>> 2)) ^ ((a[0] << 19) | (a[0] >>> 13)) ^ ((a[0] << 10) | (a[0] >>> 22))) + ((a[0] & a[1]) ^ (a[0] & a[2]) ^ (a[1] & a[2]))) | 0; a = [(t1 + t2) | 0].concat(a); a[4] = (a[4] + t1) | 0; a.pop(); } for (i = 0; i < 8; i += 1) hash[i] = (hash[i] + a[i]) | 0; }
    for (i = 0; i < 8; i += 1) for (j = 3; j + 1; j -= 1) { t1 = (hash[i] >> (j * 8)) & 255; result += String.fromCharCode(t1); } return result;
  }
  function challenge(verifier) { var digest = sha256(verifier), bytes = [], i; for (i = 0; i < digest.length; i += 1) bytes.push(digest.charCodeAt(i)); return base64Url(bytes); }

  function setStatus(label, live) { byId('connection-label').innerHTML = label; byId('status-dot').className = live ? 'status-dot live' : 'status-dot'; }
  function showError(text) { byId('setup-error').innerHTML = text; }
  function xhr(method, url, body, callback) { var req = new XMLHttpRequest(); req.open(method, url, true); if (body) req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded'); if (token && url.indexOf('api.spotify.com') !== -1) req.setRequestHeader('Authorization', 'Bearer ' + token); req.onreadystatechange = function () { if (req.readyState === 4) { var data = null; try { data = req.responseText ? JSON.parse(req.responseText) : {}; } catch (e) {} callback(req.status, data); } }; req.send(body || null); }
  function clientId() { return localStorage.getItem('spotify_client_id') || byId('client-id').value.replace(/^\s+|\s+$/g, ''); }

  function beginLogin() { var id = clientId(); if (!id) { showError('Add your Spotify Client ID to continue.'); return; } localStorage.setItem('spotify_client_id', id); var verifier = randomString(64), state = randomString(20); localStorage.setItem('spotify_code_verifier', verifier); localStorage.setItem('spotify_state', state); window.location.href = AUTH + '?' + params({ response_type: 'code', client_id: id, scope: SCOPES, code_challenge_method: 'S256', code_challenge: challenge(verifier), redirect_uri: REDIRECT, state: state }); }
  function exchange(code) { setStatus('Authorizing…', false); xhr('POST', TOKEN, params({ client_id: clientId(), grant_type: 'authorization_code', code: code, redirect_uri: REDIRECT, code_verifier: localStorage.getItem('spotify_code_verifier') }), function (status, data) { if (status !== 200 || !data.access_token) { showError('Spotify could not authorize this device. Check the Redirect URI and Client ID.'); setStatus('Not connected', false); return; } saveToken(data); window.history.replaceState({}, document.title, REDIRECT); start(); }); }
  function saveToken(data) { token = data.access_token; expiresAt = new Date().getTime() + (parseInt(data.expires_in || 3600, 10) * 1000); localStorage.setItem('spotify_access_token', token); localStorage.setItem('spotify_expires_at', expiresAt); if (data.refresh_token) localStorage.setItem('spotify_refresh_token', data.refresh_token); }
  function refresh(callback) { var refreshToken = localStorage.getItem('spotify_refresh_token'); if (!refreshToken) { callback(false); return; } xhr('POST', TOKEN, params({ client_id: clientId(), grant_type: 'refresh_token', refresh_token: refreshToken }), function (status, data) { if (status === 200 && data.access_token) { saveToken(data); callback(true); } else callback(false); }); }
  function format(ms) { var seconds = Math.max(0, Math.floor(ms / 1000)), mins = Math.floor(seconds / 60); seconds = seconds % 60; return mins + ':' + (seconds < 10 ? '0' : '') + seconds; }
  function updateProgress() { if (!current || !current.item) return; var now = current.progress_ms || 0; if (current.is_playing) now += new Date().getTime() - lastPoll; if (now > current.item.duration_ms) now = current.item.duration_ms; byId('progress-bar').style.width = ((now / current.item.duration_ms) * 100) + '%'; byId('elapsed').innerHTML = format(now); byId('duration').innerHTML = format(current.item.duration_ms); }
  function render(data) { if (!data || !data.item || data.currently_playing_type !== 'track') { current = null; byId('track-name').innerHTML = 'Nothing playing'; byId('artist-name').innerHTML = 'Start Spotify on another device'; byId('album-name').innerHTML = ''; byId('device-name').innerHTML = 'Waiting for playback'; byId('art-placeholder').className = 'art-placeholder'; byId('album-art').style.display = 'none'; byId('play-button').innerHTML = '▶'; return; } current = data; lastPoll = new Date().getTime(); var item = data.item, artists = [], i; for (i = 0; i < item.artists.length; i += 1) artists.push(item.artists[i].name); byId('track-name').innerHTML = item.name; byId('artist-name').innerHTML = artists.join(', '); byId('album-name').innerHTML = item.album.name; byId('device-name').innerHTML = data.device ? 'Playing on ' + data.device.name : 'Spotify playback'; byId('play-button').innerHTML = data.is_playing ? 'Ⅱ' : '▶'; if (item.album.images && item.album.images.length) { byId('album-art').src = item.album.images[0].url; byId('album-art').style.display = 'block'; byId('art-placeholder').className = 'art-placeholder hidden'; } updateProgress(); }
  function poll() { if (!token) return; if (expiresAt && new Date().getTime() > expiresAt - 60000) { refresh(function (ok) { if (ok) poll(); }); return; } xhr('GET', API + '/me/player/currently-playing', null, function (status, data) { if (status === 200) { setStatus('Connected', true); render(data); byId('player-message').innerHTML = 'Updates every 4 seconds'; } else if (status === 204) { setStatus('Connected', true); render(null); } else if (status === 401) { refresh(function (ok) { if (!ok) disconnect(); }); } else if (status === 429) byId('player-message').innerHTML = 'Spotify asked us to slow down — trying again soon.'; }); }
  function command(method, path, body) { if (!token) return; xhr(method, API + path, body ? JSON.stringify(body) : null, function (status) { if (status === 401) refresh(function () {}); setTimeout(poll, 500); }); }
  function start() { byId('setup-view').className = 'setup-card hidden'; byId('player-view').className = 'player-view'; poll(); if (pollTimer) clearInterval(pollTimer); pollTimer = setInterval(poll, 4000); if (progressTimer) clearInterval(progressTimer); progressTimer = setInterval(updateProgress, 500); }
  function disconnect() { token = null; localStorage.removeItem('spotify_access_token'); localStorage.removeItem('spotify_expires_at'); byId('setup-view').className = 'setup-card'; byId('player-view').className = 'player-view hidden'; setStatus('Not connected', false); }
  function init() { var query = window.location.search, code = query.match(/[?&]code=([^&]+)/), returnedState = query.match(/[?&]state=([^&]+)/), savedState = localStorage.getItem('spotify_state'); byId('client-id').value = localStorage.getItem('spotify_client_id') || ''; byId('connect-button').onclick = beginLogin; byId('disconnect-button').onclick = disconnect; byId('settings-button').onclick = function () { disconnect(); byId('client-id').focus(); }; byId('play-button').onclick = function () { command('PUT', current && current.is_playing ? '/me/player/pause' : '/me/player/play'); }; byId('next-button').onclick = function () { command('POST', '/me/player/next'); }; byId('previous-button').onclick = function () { command('POST', '/me/player/previous'); }; byId('volume-slider').onchange = function () { command('PUT', '/me/player/volume?volume_percent=' + this.value); }; if (code) { if (!returnedState || returnedState[1] !== savedState) { showError('The Spotify login state could not be verified. Please try again.'); } else exchange(decodeURIComponent(code[1])); } else if (token && (!expiresAt || new Date().getTime() < expiresAt)) start(); }
  init();
}());
