/* ES5/XHR only: compatible with Safari on iOS 9. */
(function () {
  'use strict';
  var current = null, timer, minimalist = false;
  function id(name){return document.getElementById(name)}
  function message(text){id('message').innerHTML=text}
  function request(method,url,body,done){var x=new XMLHttpRequest();x.open(method,url,true);if(body)x.setRequestHeader('Content-Type','application/json');x.onreadystatechange=function(){if(x.readyState===4){var d={};try{d=JSON.parse(x.responseText||'{}')}catch(e){}done(x.status,d)}};x.send(body?JSON.stringify(body):null)}
  function showPlayer(){id('setup').className='card hidden';id('player').className='player';id('status').innerHTML='Connected';poll()}
  function pair(){var code=id('pairing-code').value.replace(/[^a-z0-9]/ig,'').toUpperCase();if(!code){message('Enter the code shown in Safari after Spotify login.');return}message('Pairing this fullscreen app…');request('POST','/api/auth/pair',{code:code},function(status,data){if(status===200){message('');showPlayer()}else message(data.error||'Pairing failed. Try a new code.')})}
  function login(){window.location.href='/api/auth/login'}
  function formatTime(ms){if(!ms||ms<0)ms=0;var totalSec=Math.floor(ms/1000),m=Math.floor(totalSec/60),s=totalSec%60;return m+':'+(s<10?'0':'')+s}
  function updateTimeline(){if(!current||!current.item){id('timeline-fill').style.width='0%';id('time-elapsed').innerHTML='0:00';id('time-duration').innerHTML='0:00';return}var duration=current.item.duration_ms||0,elapsed=current.progress_ms||0;if(current.is_playing)elapsed+=Date.now()-current.fetched_at;if(elapsed>duration)elapsed=duration;var pct=duration?Math.min(100,elapsed/duration*100):0;id('timeline-fill').style.width=pct+'%';id('time-elapsed').innerHTML=formatTime(elapsed);id('time-duration').innerHTML=formatTime(duration)}
  function render(data){var item=data&&data.item;if(!item){id('title').innerHTML='Nothing playing';id('artist').innerHTML='Start Spotify on another device';id('album').innerHTML='';id('minimalist-artist').innerHTML='';id('minimalist-title').innerHTML='Nothing playing';id('art').style.display='none';id('placeholder').className='';id('play').innerHTML='▶';current=null;updateTimeline();return}current=data;current.fetched_at=Date.now();var artist=item.artists.map(function(a){return a.name}).join(', ');id('title').innerHTML=item.name;id('artist').innerHTML=artist;id('album').innerHTML=item.album.name;id('minimalist-artist').innerHTML=artist;id('minimalist-title').innerHTML=item.name;id('play').innerHTML=data.is_playing?'Ⅱ':'▶';if(item.album.images&&item.album.images.length){id('art').src=item.album.images[0].url;id('art').style.display='block';id('placeholder').className='hidden'}updateTimeline()}
  function poll(){request('GET','/api/spotify/currently-playing',null,function(status,data){if(status===200)render(data);else if(status===401){id('status').innerHTML='Not connected';id('player-message').innerHTML=data.error||'Pair again.'}else id('player-message').innerHTML='Waiting for Spotify…'});if(timer)clearTimeout(timer);timer=setTimeout(poll,5000)}
  function command(action){request('POST','/api/spotify/command',{action:action},function(status,data){if(status!==200)id('player-message').innerHTML=data.error||'Command failed';setTimeout(poll,400)})}
  setInterval(updateTimeline,1000);
  function createBadge(){request('POST','/api/badge/create',{},function(status,data){if(status===200){window.prompt('Copy this Markdown into your GitHub profile README:', '[![Last played on Spotify]('+data.url+')](https://'+window.location.host+'/)')}else id('player-message').innerHTML=data.error||'Could not create badge.'})}
  function escapeHtml(text){return text.replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function openArtistModal(){id('artist-modal').className='modal';id('artist-query').value='';id('artist-results').innerHTML='';id('artist-message').innerHTML='';id('artist-query').focus()}
  function closeArtistModal(){id('artist-modal').className='modal hidden'}
  function searchArtist(){var q=id('artist-query').value.trim();if(!q){id('artist-message').innerHTML='Enter an artist name.';return}id('artist-message').innerHTML='Searching…';id('artist-results').innerHTML='';request('GET','/api/spotify/search-artist?q='+encodeURIComponent(q),null,function(status,data){if(status!==200){id('artist-message').innerHTML=data.error||'Search failed.';return}var artists=data.artists||[];if(!artists.length){id('artist-message').innerHTML='No artists found.';return}id('artist-message').innerHTML='';var html='';for(var i=0;i<artists.length;i++){html+='<button type="button" class="artist-result" data-id="'+artists[i].id+'">'+escapeHtml(artists[i].name)+'</button>'}id('artist-results').innerHTML=html;var buttons=id('artist-results').getElementsByTagName('button');for(var j=0;j<buttons.length;j++){buttons[j].onclick=function(){playArtist(this.getAttribute('data-id'),this.innerHTML)}}})}
  function playArtist(artistId,name){id('artist-message').innerHTML='Starting '+name+' radio…';request('POST','/api/spotify/command',{action:'play_artist',artist_id:artistId},function(status,data){if(status!==200){id('artist-message').innerHTML=data.error||'Could not start artist radio.';return}closeArtistModal();setTimeout(poll,600)})}
  function enterMinimalist(){minimalist=true;document.body.className='minimalist';id('minimalist').innerHTML='Regular View'}
  function exitMinimalist(){minimalist=false;document.body.className='';id('exit-modal').className='modal hidden';id('minimalist').innerHTML='Minimalist View'}
  id('login').onclick=login;id('pair').onclick=pair;id('pairing-code').onkeyup=function(e){if(e&&e.keyCode===13)pair()};id('previous').onclick=function(){command('previous')};id('next').onclick=function(){command('next')};id('play').onclick=function(){command(current&&current.is_playing?'pause':'play')};id('minimalist').onclick=function(){if(minimalist)exitMinimalist();else enterMinimalist()};id('badge').onclick=createBadge;id('art-tap').onclick=function(){if(minimalist)id('exit-modal').className='modal';};id('exit-yes').onclick=exitMinimalist;id('exit-no').onclick=function(){id('exit-modal').className='modal hidden'};id('disconnect').onclick=function(){request('POST','/api/auth/logout',null,function(){location.reload()})};id('search-artist').onclick=openArtistModal;id('artist-search-go').onclick=searchArtist;id('artist-cancel').onclick=closeArtistModal;id('artist-query').onkeyup=function(e){if(e&&e.keyCode===13)searchArtist()};
  request('GET','/api/spotify/currently-playing',null,function(status){if(status===200)showPlayer()});
}());
