var test = require('node:test');
var assert = require('node:assert');
var path = require('node:path');
var helpers = require('./helpers');

var lib = require(path.join('..', 'api', '_lib.js'));
var pair = require(path.join('..', 'api', 'auth', 'pair.js'));

function stubLib(overrides) {
  var originals = {};
  Object.keys(overrides).forEach(function (key) { originals[key] = lib[key]; lib[key] = overrides[key]; });
  return function restore() { Object.keys(originals).forEach(function (key) { lib[key] = originals[key]; }); };
}

function notLimited(req, bucket, limit, seconds, cb) { cb(null, false); }

test('rejects non-POST requests with 405', function () {
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('GET', '/api/auth/pair'), res);
  assert.strictEqual(res.statusCode, 405);
});

test('rejects a code that is too short', function () {
  var restore = stubLib({ rateLimit: notLimited });
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('POST', '/api/auth/pair', null, { code: 'AB' }), res);
  restore();
  assert.strictEqual(res.statusCode, 400);
});

test('rejects an unknown or expired code', function () {
  var restore = stubLib({ rateLimit: notLimited, kvGet: function (key, cb) { cb(null, null); } });
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('POST', '/api/auth/pair', null, { code: 'ABCD1234' }), res);
  restore();
  assert.strictEqual(res.statusCode, 401);
  assert.match(helpers.resBody(res).error, /invalid or expired/i);
});

test('accepts a valid, unexpired pairing-code generated by lib.pairingCode and starts a session', function (t, done) {
  var code = lib.pairingCode(8);
  var deletedKey = null, savedSession = null;
  var restore = stubLib({
    rateLimit: notLimited,
    kvGet: function (key, cb) { cb(null, { refresh_token: 'refresh-token', expires: Date.now() + 60000 }); },
    kvDel: function (key, cb) { deletedKey = key; cb(null); },
    kvSet: function (key, value, seconds, cb) { savedSession = { key: key, value: value }; cb(null); }
  });
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('POST', '/api/auth/pair', null, { code: code }), res);
  setImmediate(function () {
    restore();
    assert.strictEqual(deletedKey, 'pair:' + code);
    assert.ok(savedSession.key.indexOf('session:') === 0);
    assert.strictEqual(savedSession.value.refresh_token, 'refresh-token');
    assert.strictEqual(res.statusCode, 200);
    assert.strictEqual(helpers.resBody(res).connected, true);
    done();
  });
});

test('rejects an expired code even if still present in storage', function () {
  var restore = stubLib({ rateLimit: notLimited, kvGet: function (key, cb) { cb(null, { refresh_token: 'x', expires: Date.now() - 1000 }); } });
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('POST', '/api/auth/pair', null, { code: 'ABCD1234' }), res);
  restore();
  assert.strictEqual(res.statusCode, 401);
});

test('returns 429 when rate limited', function () {
  var restore = stubLib({ rateLimit: function (req, bucket, limit, seconds, cb) { cb(null, true); } });
  var res = helpers.fakeRes();
  pair(helpers.fakeReq('POST', '/api/auth/pair', null, { code: 'ABCD1234' }), res);
  restore();
  assert.strictEqual(res.statusCode, 429);
});
